### ISSUE TITLE
As an event planner and caterer, I want to filter my guests based on dietary requirements,

### ISSUE THREAD

**Issue by aaryam253** [CS2113-AY1819S1-F09-3/main#13]
so that I can plan my event accordingly.

**Comment by SarahTaaherBonna** [comment]
To do: 
1. Create a Dietary attribute
2. Edit the commands (e.g. Filter Command) and parsers (e.g. Filter Command Parser) that require dietary as a person's attribute
3. Add tests to make sure the attribute functions as expected.
