### ISSUE TITLE
As an event planner specialising in concerts, I want to be able to filter my guests to see who have not paid for the event, 

### ISSUE THREAD

**Issue by aaryam253** [CS2113-AY1819S1-F09-3/main#9]
so that I can easily see who I need to remind.

**Comment by SarahTaaherBonna** [comment]
To do: 
1. Create a Payment attribute
2. Edit the commands (e.g. Filter Command) and parsers (e.g. Filter Command Parser) that require payment as a person's attribute
3. Add tests to make sure the attribute functions as expected.
